# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cpauwels <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/06/07 07:08:27 by cpauwels          #+#    #+#              #
#    Updated: 2017/09/04 09:20:42 by cpauwels         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = ft_memchr.c ft_atoi.c ft_memcmp.c ft_memalloc.c ft_putchar.c\
	ft_bzero.c ft_memcpy.c ft_memdel.c ft_strnew.c ft_strequ.c ft_putnbr.c\
	ft_strrchr.c ft_isalnum.c ft_strcat.c ft_strlcat.c ft_strjoin.c\
	ft_isalpha.c ft_memmove.c ft_strchr.c ft_strlen.c ft_strstr.c\
	ft_isascii.c ft_memset.c ft_isdigit.c ft_strmap.c ft_strnequ.c\
	ft_strcmp.c ft_isprint.c ft_strdel.c ft_striter.c ft_strsub.c\
	ft_strcpy.c ft_strncat.c ft_tolower.c ft_strmapi.c ft_strsplit.c\
	ft_strncmp.c ft_toupper.c ft_strdup.c ft_strncpy.c ft_strtrim.c\
	ft_memccpy.c ft_strnstr.c ft_strclr.c ft_striteri.c ft_putstr.c ft_itoa.c\
	ft_putendl.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c\
	ft_lstnew.c ft_lstdelone.c ft_lstdel.c ft_lstadd.c ft_lstiter.c ft_lstmap.c get_next_line.c \
	ft_strnjoin.c ft_isnumber.c
	
OBJ = ft_memchr.o ft_atoi.o ft_memcmp.o ft_memalloc.o ft_putchar.o\
	ft_bzero.o ft_memcpy.o ft_memdel.o ft_strnew.o ft_strequ.o ft_putnbr.o\
	ft_strrchr.o ft_isalnum.o ft_strcat.o ft_strlcat.o ft_strjoin.o\
	ft_isalpha.o ft_memmove.o ft_strchr.o ft_strlen.o ft_strstr.o\
	ft_isascii.o ft_memset.o ft_isdigit.o ft_strmap.o ft_strnequ.o\
	ft_strcmp.o ft_isprint.o ft_strdel.o ft_striter.o ft_strsub.o\
	ft_strcpy.o ft_strncat.o ft_tolower.o ft_strmapi.o ft_strsplit.o\
	ft_strncmp.o ft_toupper.o ft_strdup.o ft_strncpy.o ft_strtrim.o\
	ft_memccpy.o ft_strnstr.o ft_strclr.o ft_striteri.o ft_putstr.o ft_itoa.o\
	ft_putendl.o ft_putchar_fd.o ft_putstr_fd.o ft_putendl_fd.o ft_putnbr_fd.o\
	ft_lstnew.o ft_lstdelone.o ft_lstdel.o ft_lstadd.o ft_lstiter.o ft_lstmap.o get_next_line.o \
	ft_strnjoin.o ft_isnumber.o

NAME  = libft.a

NONE = \x1b[0m
OK = \x1b[32;01m
WARN = \x1b[33;01m

FLAGS = -Wall -Wextra -Werror

all:
	@echo "$(OK)----------  Compile Libft  ----------$(NONE)"
	@gcc -c $(FLAGS) $(SRCS)
	@ar rc $(NAME) $(OBJ)
	@ranlib libft.a
	@echo "$(OK)----------     Success     ----------$(NONE)\n"

clean:
	@echo "$(WARN)----------   Clean Libft   ----------$(NONE)"
	@rm -f $(OBJ)
	@echo "Removed Object Files"
	@echo "$(WARN)----------     Success     ----------$(NONE)\n"
	

fclean:
	@echo "$(WARN)----------   Clean Libft   ----------$(NONE)"
	@rm -f $(OBJ)
	@echo "Removed Object Files"
	@rm -f $(NAME)
	@echo "Removed Libft Files"
	@echo "$(WARN)----------     Success     ----------$(NONE)\n"
	

re : fclean all
